server:
  port: 8089

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:6432/electron_queue
    username: postgres
    password: postgres

  flyway:
    password: postgres
    user: postgres
    url: jdbc:postgresql://localhost:6432/electron_queue

  data:
    redis:
      host: localhost
      port: 6380
      password: password
      ssl: true

  mail:
    host: smtp.gmail.com
    port: 465
    username: tretyakmd@gmail.com
    password: ${GMAIL_VKRB_PASSWORD}
    properties:
      "mail.transport.protocol": smtps
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.ssl.enable": true
    protocol: smtps